"""Constants specific to CLI functionality."""

MIN_CLI_ARGS = 2

ENUMERATE_START = 1

SEPARATOR_LENGTH = 60
SEPARATOR_CHAR = "="
ALT_SEPARATOR_CHAR = "-"

SCORE_DECIMAL_PLACES = 4
MIN_SCORE = 0
MAX_SCORE_COSINE = 1
MAX_SCORE_DISTANCE = 2

EXIT_CODE_SUCCESS = 0
EXIT_CODE_ERROR = 1

